//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsAttendenceManagementProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string StudentName { get; set; }
        public string RollNo { get; set; }
        public string Percentage { get; set; }
    }
}
