//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Display_CurrentDate_using_Web_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentDateview
    {
        public System.DateTime TodayDate { get; set; }
    }
}
